/**
 * Report Generator - Creates Markdown reports from knowledge-base data only
 * Runs daily via GitHub Actions
 */

import './load-env.ts';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface CollectionSummary {
  date: string;
  newItems: number;
  totalItems: number;
  bySource: Record<string, number>;
  byCategory?: Record<string, number>;
  topTopics: Record<string, number>;
  brandMentions?: number;
}

const DATA_DIR = path.join(__dirname, '..', '..', 'data');
const REPORTS_DIR = path.join(__dirname, '..', '..', 'data', 'reports');
const ARTICLES_DIR = path.join(__dirname, '..', '..', 'src', 'content', 'articles');

async function ensureDirs(): Promise<void> {
  await fs.mkdir(REPORTS_DIR, { recursive: true });
}

async function loadKnowledgeBaseSummary(): Promise<CollectionSummary | null> {
  const filePath = path.join(DATA_DIR, 'knowledge-base', 'collection-summary.json');
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

function mdRow(values: string[]): string {
  return `| ${values.join(' | ')} |`;
}

function generateMarkdownReport(date: string, generatedAt: string, kbSummary: CollectionSummary | null, generatedArticles: string[]): string {
  const lines: string[] = [];
  lines.push(`# SEO Report - ${date}`);
  lines.push('');
  lines.push(`Generated: ${new Date(generatedAt).toLocaleString()}`);
  lines.push('');

  if (kbSummary) {
    lines.push('## Knowledge Base Updates');
    lines.push(mdRow(['Metric', 'Value']));
    lines.push(mdRow(['---', '---']));
    lines.push(mdRow(['New Items Today', kbSummary.newItems.toString()]));
    lines.push(mdRow(['Total Items', kbSummary.totalItems.toString()]));
    if (typeof kbSummary.brandMentions === 'number') {
      lines.push(mdRow(['Brand Mentions (Openclaw/Moltbot/Clawdbot)', kbSummary.brandMentions.toString()]));
    }
    lines.push(mdRow(['Sources', Object.entries(kbSummary.bySource).map(([source, count]) => `${source}: ${count}`).join(' | ')]));
    if (kbSummary.byCategory) {
      lines.push(mdRow(['Content Types', Object.entries(kbSummary.byCategory).map(([category, count]) => `${category}: ${count}`).join(' | ')]));
    }
    lines.push(mdRow(['Top Topics', Object.entries(kbSummary.topTopics).slice(0, 5).map(([topic, count]) => `${topic} (${count})`).join(', ')]));
    lines.push('');
  }

  lines.push('## Generated Articles');
  if (generatedArticles.length === 0) {
    lines.push('- No new articles generated today.');
  } else {
    lines.push(`- Total: ${generatedArticles.length}`);
    generatedArticles.forEach((slug) => {
      lines.push(`  - ${slug}`);
    });
  }
  lines.push('');

  lines.push('---');
  lines.push('This report is automatically generated by the SEO Automation System.');
  lines.push(`© ${new Date().getFullYear()} Openclaw (Moltbot/Clawdbot)`);

  return lines.join('\n');
}


async function loadGeneratedArticles(): Promise<string[]> {
  const filePath = path.join(DATA_DIR, 'knowledge-base', 'generated-articles.json');
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    const parsed = JSON.parse(content);
    if (Array.isArray(parsed)) return parsed.filter((item) => typeof item === 'string');
    return [];
  } catch {
    return [];
  }
}

async function loadGeneratedArticleTitles(slugs: string[]): Promise<Record<string, string>> {
  const titles: Record<string, string> = {};
  for (const slug of slugs) {
    const filePath = path.join(ARTICLES_DIR, `${slug}.mdx`);
    try {
      const content = await fs.readFile(filePath, 'utf-8');
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (!frontmatterMatch) continue;
      const titleMatch = frontmatterMatch[1].match(/title:\s*(?:"([^"]+)"|'([^']+)'|(.+))$/m);
      const title = titleMatch?.[1] || titleMatch?.[2] || titleMatch?.[3];
      if (title) titles[slug] = title.trim();
    } catch {
      // Ignore missing files.
    }
  }
  return titles;
}

async function generateReport(): Promise<void> {
  console.log('Generating daily report...');
  console.log('Date:', new Date().toISOString());

  await ensureDirs();

  const targetDate = process.env.SEO_DATE || process.env.ANALYTICS_DATE || new Date().toISOString().split('T')[0];
  const generatedAt = new Date().toISOString();

  // Load knowledge base summary
  const kbSummary = await loadKnowledgeBaseSummary();

  // Load generated articles (slugs)
  const generatedArticles = await loadGeneratedArticles();
  const titles = await loadGeneratedArticleTitles(generatedArticles);
  const formattedArticles = generatedArticles.map((slug) => (titles[slug] ? `${titles[slug]} (${slug})` : slug));

  // Generate report markdown
  const reportContent = generateMarkdownReport(targetDate, generatedAt, kbSummary, formattedArticles);

  // Save report
  const reportFileName = `${targetDate}.md`;
  const reportPath = path.join(REPORTS_DIR, reportFileName);
  await fs.writeFile(reportPath, reportContent);

  console.log(`Report saved to: ${reportPath}`);

  console.log('\nReport generation complete!');
}

// Run
generateReport().catch(console.error);
